version: '3.8'
services:
  postgres:
    image: postgres
    container_name: "thread_db"
    ports:
      - 5432:5432
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: threads
      POSTGRES_PASSWORD: threads 
volumes:
  postgres_data:

    
