version: '3.8'
services:
  postgres:
    image: postgres
    container_name: "thread_db"
    ports:
      - 5433:5432
    volumes:
      - "postgres_db_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: thread_database
      POSTGRES_PASSWORD: DevPractice18 
volumes:
  postgres_db_data:

    
